### ISSUE TITLE
회원가입 버튼이 눌러도 아무 반응이 없습니다. 

### ISSUE THREAD

**Issue by dongjangoon** [wafflestudio19-5/team6-web#33]
![image](https://user-images.githubusercontent.com/56782035/148633629-6a7a4b50-23ec-4a09-a5a5-1cd9d8151288.png)

시연 때도 나왔는데 여기서 안 넘어가는 버그가 있습니다!

**Comment by HyeongtaekOh** [comment]
해결해서 새로 배포했는데 아직 문제 발생하시나요??

**Comment by numnum97** [comment]
아뇨 잘 됩니다! 감사합니다 :)
