### ISSUE TITLE
동네 위치 설정 이슈

### ISSUE THREAD

**Issue by xxnpark** [wafflestudio19-5/team6-web#38]
![image](https://user-images.githubusercontent.com/52618646/148635786-586faa76-b07a-419b-9ec2-0eed786a1a96.png)
![image](https://user-images.githubusercontent.com/52618646/148635807-59ad1144-1483-4ae0-8865-1fac05fcd1cb.png)

처음 가입 시 위치를 기반으로 동네 설정을 했는데, 그와 별개로 홈에서는 '301동'이라고 뜨네요! 검색창에도 '낙성대동 근처에서 검색'이라고 뜹니다.

**Comment by s-yeoyul** [comment]
#51 수정했습니다!
