### ISSUE TITLE
Bug: 글 작성 대기 시간 중 버튼을 여러 번 누르면 그만큼 글이 새로 작성되는 문제

### ISSUE THREAD

**Issue by HunRotation** [wafflestudio19-5/team6-web#40]
![image](https://user-images.githubusercontent.com/48827296/148639022-b7db28ee-c0e9-4010-a383-3cea1e41aae1.png)

이미지 등의 처리를 위해서 글을 작성하고 작성 버튼을 누르면 작성이 완료되기까지 약간의 시간이 필요한 것으로 보입니다. 그런데, 그 시간 동안 작성 버튼을 여러 번 클릭하면 사진과 같이 동일한 내용의 글이 여러 개 작성됩니다.

**Comment by s-yeoyul** [comment]
#50 수정했습니다!
